version: "3"
services:
        db:
                image: mysql:latest
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_USER=jpatest
                        - MYSQL_PASSWORD=jpapw
                        - MYSQL_DATABASE=jpatest
                ports:
                        - "3306:3306"
                volumes:
                        - db-data:/var/lib/mysql

        webapp:
                depends_on:
                        - db
                build:
                        context: .
                links:
                        - db

volumes:
        db-data:

