version: "3"
services:
        db:
                image: postgres:latest
                restart: always
                environment:
                        - POSTGRES_PASSWORD=jpapw
                ports:
                        - "5432:5432"

        webapp:
                depends_on:
                        - db
                build:
                        context: .
                ports:
                        - 8080:8080
                links:
                        - db
                command: ["./wait-for-it.sh", "db:5432", "java", "-jar", "/app.jar"]
                
        adminer:
                image: adminer
                restart: always
                ports:
                        - 9000:8080


